LOCAL_PATH := $(call my-dir)

ifeq ($(DASHCHAN_FFMPEG_FLAVOR),ffmpeg8)
LOCAL_FFMPEG_REL_PATH := ../ffmpeg8
ifneq ($(DASHCHAN_WEBM_SHARED_LIBRARIES),)
LOCAL_FFMPEG_PREBUILT_ROOT := $(DASHCHAN_WEBM_SHARED_LIBRARIES)
endif
else
LOCAL_FFMPEG_REL_PATH := .
endif

ifneq ($(LOCAL_FFMPEG_PREBUILT_ROOT),)
include $(CLEAR_VARS)
LOCAL_MODULE := dav1d
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/dav1d/$(TARGET_ARCH_ABI)/libdav1d.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := avcodec
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/ffmpeg/$(TARGET_ARCH_ABI)/libavcodec.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
LOCAL_SHARED_LIBRARIES := dav1d
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := avformat
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/ffmpeg/$(TARGET_ARCH_ABI)/libavformat.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := avutil
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/ffmpeg/$(TARGET_ARCH_ABI)/libavutil.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := swresample
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/ffmpeg/$(TARGET_ARCH_ABI)/libswresample.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := swscale
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/ffmpeg/$(TARGET_ARCH_ABI)/libswscale.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(PREBUILT_SHARED_LIBRARY)

ifeq ($(DASHCHAN_FFMPEG_FLAVOR),ffmpeg8)
include $(CLEAR_VARS)
LOCAL_MODULE := avfilter
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_PREBUILT_ROOT)/ffmpeg/$(TARGET_ARCH_ABI)/libavfilter.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
LOCAL_SHARED_LIBRARIES := avutil
include $(PREBUILT_SHARED_LIBRARY)
endif

else
include $(CLEAR_VARS)
LOCAL_MODULE := avcodec
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_REL_PATH)/symbols/$(TARGET_ARCH_ABI)/libavcodec.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := avformat
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_REL_PATH)/symbols/$(TARGET_ARCH_ABI)/libavformat.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := avutil
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_REL_PATH)/symbols/$(TARGET_ARCH_ABI)/libavutil.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := swresample
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_REL_PATH)/symbols/$(TARGET_ARCH_ABI)/libswresample.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := swscale
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_REL_PATH)/symbols/$(TARGET_ARCH_ABI)/libswscale.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
include $(BUILD_SHARED_LIBRARY)

ifeq ($(DASHCHAN_FFMPEG_FLAVOR),ffmpeg8)
include $(CLEAR_VARS)
LOCAL_MODULE := avfilter
LOCAL_SRC_FILES := $(LOCAL_FFMPEG_REL_PATH)/symbols/$(TARGET_ARCH_ABI)/libavfilter.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(LOCAL_FFMPEG_REL_PATH)/include/$(TARGET_ARCH_ABI)
LOCAL_SHARED_LIBRARIES := avutil
include $(BUILD_SHARED_LIBRARY)
endif

endif
