LOCAL_PATH := $(call my-dir)

ifeq ($(DASHCHAN_FFMPEG_FLAVOR),ffmpeg8)
ifneq ($(DASHCHAN_WEBM_SHARED_LIBRARIES),)
LOCAL_YUV_PREBUILT_ROOT := $(DASHCHAN_WEBM_SHARED_LIBRARIES)
endif
endif

ifneq ($(LOCAL_YUV_PREBUILT_ROOT),)
include $(CLEAR_VARS)
LOCAL_MODULE := yuv
LOCAL_SRC_FILES := $(LOCAL_YUV_PREBUILT_ROOT)/yuv/$(TARGET_ARCH_ABI)/libyuv.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
include $(PREBUILT_SHARED_LIBRARY)

else
include $(CLEAR_VARS)
LOCAL_MODULE := yuv
LOCAL_SRC_FILES := symbols/$(TARGET_ARCH_ABI)/libyuv.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
include $(BUILD_SHARED_LIBRARY)

endif
